services:
  app:
    image: ghcr.io/majsvaffla/dax:latest
    ports:
      - 8001:8000
    volumes:
      - /var/lib/ärdetdags/instance:/var/lib/ärdetdags/instance
    environment:
      SENTRY_DSN: ${SENTRY_DSN}
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 dax:app
    restart: unless-stopped
